//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.UI.EmlakServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/Emlak.Entities")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Müsteri", Namespace="http://schemas.datacontract.org/2004/07/Emlak.Entities")]
    [System.SerializableAttribute()]
    public partial class Müsteri : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MüsteriAdıField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MüsteriIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MüsteriMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MüsteriSoyadıField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MüsteriTcField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MüsteriAdı {
            get {
                return this.MüsteriAdıField;
            }
            set {
                if ((object.ReferenceEquals(this.MüsteriAdıField, value) != true)) {
                    this.MüsteriAdıField = value;
                    this.RaisePropertyChanged("MüsteriAdı");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MüsteriId {
            get {
                return this.MüsteriIdField;
            }
            set {
                if ((this.MüsteriIdField.Equals(value) != true)) {
                    this.MüsteriIdField = value;
                    this.RaisePropertyChanged("MüsteriId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MüsteriMail {
            get {
                return this.MüsteriMailField;
            }
            set {
                if ((object.ReferenceEquals(this.MüsteriMailField, value) != true)) {
                    this.MüsteriMailField = value;
                    this.RaisePropertyChanged("MüsteriMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MüsteriSoyadı {
            get {
                return this.MüsteriSoyadıField;
            }
            set {
                if ((object.ReferenceEquals(this.MüsteriSoyadıField, value) != true)) {
                    this.MüsteriSoyadıField = value;
                    this.RaisePropertyChanged("MüsteriSoyadı");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MüsteriTc {
            get {
                return this.MüsteriTcField;
            }
            set {
                if ((this.MüsteriTcField.Equals(value) != true)) {
                    this.MüsteriTcField = value;
                    this.RaisePropertyChanged("MüsteriTc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Daire", Namespace="http://schemas.datacontract.org/2004/07/Emlak.Entities")]
    [System.SerializableAttribute()]
    public partial class Daire : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DaireAdıField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DaireIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DaireSayısıField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DaireAdı {
            get {
                return this.DaireAdıField;
            }
            set {
                if ((object.ReferenceEquals(this.DaireAdıField, value) != true)) {
                    this.DaireAdıField = value;
                    this.RaisePropertyChanged("DaireAdı");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DaireId {
            get {
                return this.DaireIdField;
            }
            set {
                if ((this.DaireIdField.Equals(value) != true)) {
                    this.DaireIdField = value;
                    this.RaisePropertyChanged("DaireId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DaireSayısı {
            get {
                return this.DaireSayısıField;
            }
            set {
                if ((this.DaireSayısıField.Equals(value) != true)) {
                    this.DaireSayısıField = value;
                    this.RaisePropertyChanged("DaireSayısı");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Odalar", Namespace="http://schemas.datacontract.org/2004/07/Emlak.Entities")]
    [System.SerializableAttribute()]
    public partial class Odalar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OdaAdıField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OdaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OdaSayısıField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OdaAdı {
            get {
                return this.OdaAdıField;
            }
            set {
                if ((object.ReferenceEquals(this.OdaAdıField, value) != true)) {
                    this.OdaAdıField = value;
                    this.RaisePropertyChanged("OdaAdı");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OdaId {
            get {
                return this.OdaIdField;
            }
            set {
                if ((this.OdaIdField.Equals(value) != true)) {
                    this.OdaIdField = value;
                    this.RaisePropertyChanged("OdaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OdaSayısı {
            get {
                return this.OdaSayısıField;
            }
            set {
                if ((this.OdaSayısıField.Equals(value) != true)) {
                    this.OdaSayısıField = value;
                    this.RaisePropertyChanged("OdaSayısı");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MalSahibi", Namespace="http://schemas.datacontract.org/2004/07/Emlak.Entities")]
    [System.SerializableAttribute()]
    public partial class MalSahibi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SahipAdıField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SahipEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SahipIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SahipSoyadıField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SahipTcField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SahipAdı {
            get {
                return this.SahipAdıField;
            }
            set {
                if ((object.ReferenceEquals(this.SahipAdıField, value) != true)) {
                    this.SahipAdıField = value;
                    this.RaisePropertyChanged("SahipAdı");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SahipEmail {
            get {
                return this.SahipEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.SahipEmailField, value) != true)) {
                    this.SahipEmailField = value;
                    this.RaisePropertyChanged("SahipEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SahipId {
            get {
                return this.SahipIdField;
            }
            set {
                if ((this.SahipIdField.Equals(value) != true)) {
                    this.SahipIdField = value;
                    this.RaisePropertyChanged("SahipId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SahipSoyadı {
            get {
                return this.SahipSoyadıField;
            }
            set {
                if ((object.ReferenceEquals(this.SahipSoyadıField, value) != true)) {
                    this.SahipSoyadıField = value;
                    this.RaisePropertyChanged("SahipSoyadı");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SahipTc {
            get {
                return this.SahipTcField;
            }
            set {
                if ((this.SahipTcField.Equals(value) != true)) {
                    this.SahipTcField = value;
                    this.RaisePropertyChanged("SahipTc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kiralık", Namespace="http://schemas.datacontract.org/2004/07/Emlak.Entities")]
    [System.SerializableAttribute()]
    public partial class Kiralık : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> KiraFiyatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> KiraTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KiralıkIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> KiraFiyat {
            get {
                return this.KiraFiyatField;
            }
            set {
                if ((this.KiraFiyatField.Equals(value) != true)) {
                    this.KiraFiyatField = value;
                    this.RaisePropertyChanged("KiraFiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> KiraTarihi {
            get {
                return this.KiraTarihiField;
            }
            set {
                if ((this.KiraTarihiField.Equals(value) != true)) {
                    this.KiraTarihiField = value;
                    this.RaisePropertyChanged("KiraTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KiralıkId {
            get {
                return this.KiralıkIdField;
            }
            set {
                if ((this.KiralıkIdField.Equals(value) != true)) {
                    this.KiralıkIdField = value;
                    this.RaisePropertyChanged("KiralıkId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Satılık", Namespace="http://schemas.datacontract.org/2004/07/Emlak.Entities")]
    [System.SerializableAttribute()]
    public partial class Satılık : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SatılıkFiyatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SatılıkIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SatılıkFiyat {
            get {
                return this.SatılıkFiyatField;
            }
            set {
                if ((this.SatılıkFiyatField.Equals(value) != true)) {
                    this.SatılıkFiyatField = value;
                    this.RaisePropertyChanged("SatılıkFiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SatılıkId {
            get {
                return this.SatılıkIdField;
            }
            set {
                if ((this.SatılıkIdField.Equals(value) != true)) {
                    this.SatılıkIdField = value;
                    this.RaisePropertyChanged("SatılıkId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmlakServiceReference.IEmlakService")]
    public interface IEmlakService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/GetUsers", ReplyAction="http://tempuri.org/IEmlakService/GetUsersResponse")]
        Emlak.UI.EmlakServiceReference.Users GetUsers(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/GetUsers", ReplyAction="http://tempuri.org/IEmlakService/GetUsersResponse")]
        System.Threading.Tasks.Task<Emlak.UI.EmlakServiceReference.Users> GetUsersAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/GetMüsteris", ReplyAction="http://tempuri.org/IEmlakService/GetMüsterisResponse")]
        Emlak.UI.EmlakServiceReference.Müsteri[] GetMüsteris();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/GetMüsteris", ReplyAction="http://tempuri.org/IEmlakService/GetMüsterisResponse")]
        System.Threading.Tasks.Task<Emlak.UI.EmlakServiceReference.Müsteri[]> GetMüsterisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/GetDaires", ReplyAction="http://tempuri.org/IEmlakService/GetDairesResponse")]
        Emlak.UI.EmlakServiceReference.Daire[] GetDaires();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/GetDaires", ReplyAction="http://tempuri.org/IEmlakService/GetDairesResponse")]
        System.Threading.Tasks.Task<Emlak.UI.EmlakServiceReference.Daire[]> GetDairesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/GetOdalars", ReplyAction="http://tempuri.org/IEmlakService/GetOdalarsResponse")]
        Emlak.UI.EmlakServiceReference.Odalar[] GetOdalars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/GetOdalars", ReplyAction="http://tempuri.org/IEmlakService/GetOdalarsResponse")]
        System.Threading.Tasks.Task<Emlak.UI.EmlakServiceReference.Odalar[]> GetOdalarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/AddMüsteri", ReplyAction="http://tempuri.org/IEmlakService/AddMüsteriResponse")]
        void AddMüsteri(Emlak.UI.EmlakServiceReference.Müsteri müsteri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/AddMüsteri", ReplyAction="http://tempuri.org/IEmlakService/AddMüsteriResponse")]
        System.Threading.Tasks.Task AddMüsteriAsync(Emlak.UI.EmlakServiceReference.Müsteri müsteri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/RemoveMüsteri", ReplyAction="http://tempuri.org/IEmlakService/RemoveMüsteriResponse")]
        void RemoveMüsteri(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/RemoveMüsteri", ReplyAction="http://tempuri.org/IEmlakService/RemoveMüsteriResponse")]
        System.Threading.Tasks.Task RemoveMüsteriAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/EditMüsteri", ReplyAction="http://tempuri.org/IEmlakService/EditMüsteriResponse")]
        void EditMüsteri(Emlak.UI.EmlakServiceReference.Müsteri müsteri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/EditMüsteri", ReplyAction="http://tempuri.org/IEmlakService/EditMüsteriResponse")]
        System.Threading.Tasks.Task EditMüsteriAsync(Emlak.UI.EmlakServiceReference.Müsteri müsteri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/AddOda", ReplyAction="http://tempuri.org/IEmlakService/AddOdaResponse")]
        void AddOda(Emlak.UI.EmlakServiceReference.Odalar odalar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/AddOda", ReplyAction="http://tempuri.org/IEmlakService/AddOdaResponse")]
        System.Threading.Tasks.Task AddOdaAsync(Emlak.UI.EmlakServiceReference.Odalar odalar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/RemoveOda", ReplyAction="http://tempuri.org/IEmlakService/RemoveOdaResponse")]
        void RemoveOda(Emlak.UI.EmlakServiceReference.Odalar odalar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/RemoveOda", ReplyAction="http://tempuri.org/IEmlakService/RemoveOdaResponse")]
        System.Threading.Tasks.Task RemoveOdaAsync(Emlak.UI.EmlakServiceReference.Odalar odalar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/EditOda", ReplyAction="http://tempuri.org/IEmlakService/EditOdaResponse")]
        void EditOda(Emlak.UI.EmlakServiceReference.Odalar odalar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/EditOda", ReplyAction="http://tempuri.org/IEmlakService/EditOdaResponse")]
        System.Threading.Tasks.Task EditOdaAsync(Emlak.UI.EmlakServiceReference.Odalar odalar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/AddDaire", ReplyAction="http://tempuri.org/IEmlakService/AddDaireResponse")]
        void AddDaire(Emlak.UI.EmlakServiceReference.Daire daire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/AddDaire", ReplyAction="http://tempuri.org/IEmlakService/AddDaireResponse")]
        System.Threading.Tasks.Task AddDaireAsync(Emlak.UI.EmlakServiceReference.Daire daire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/RemoveDaire", ReplyAction="http://tempuri.org/IEmlakService/RemoveDaireResponse")]
        void RemoveDaire(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/RemoveDaire", ReplyAction="http://tempuri.org/IEmlakService/RemoveDaireResponse")]
        System.Threading.Tasks.Task RemoveDaireAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/EditDaire", ReplyAction="http://tempuri.org/IEmlakService/EditDaireResponse")]
        void EditDaire(Emlak.UI.EmlakServiceReference.Daire daire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/EditDaire", ReplyAction="http://tempuri.org/IEmlakService/EditDaireResponse")]
        System.Threading.Tasks.Task EditDaireAsync(Emlak.UI.EmlakServiceReference.Daire daire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/GetMalSahibis", ReplyAction="http://tempuri.org/IEmlakService/GetMalSahibisResponse")]
        Emlak.UI.EmlakServiceReference.MalSahibi[] GetMalSahibis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/GetMalSahibis", ReplyAction="http://tempuri.org/IEmlakService/GetMalSahibisResponse")]
        System.Threading.Tasks.Task<Emlak.UI.EmlakServiceReference.MalSahibi[]> GetMalSahibisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/AddMalSahibi", ReplyAction="http://tempuri.org/IEmlakService/AddMalSahibiResponse")]
        void AddMalSahibi(Emlak.UI.EmlakServiceReference.MalSahibi malSahibi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/AddMalSahibi", ReplyAction="http://tempuri.org/IEmlakService/AddMalSahibiResponse")]
        System.Threading.Tasks.Task AddMalSahibiAsync(Emlak.UI.EmlakServiceReference.MalSahibi malSahibi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/RemoveMalSahibi", ReplyAction="http://tempuri.org/IEmlakService/RemoveMalSahibiResponse")]
        void RemoveMalSahibi(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/RemoveMalSahibi", ReplyAction="http://tempuri.org/IEmlakService/RemoveMalSahibiResponse")]
        System.Threading.Tasks.Task RemoveMalSahibiAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/EditMalSahibi", ReplyAction="http://tempuri.org/IEmlakService/EditMalSahibiResponse")]
        void EditMalSahibi(Emlak.UI.EmlakServiceReference.MalSahibi malSahibi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/EditMalSahibi", ReplyAction="http://tempuri.org/IEmlakService/EditMalSahibiResponse")]
        System.Threading.Tasks.Task EditMalSahibiAsync(Emlak.UI.EmlakServiceReference.MalSahibi malSahibi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/GetKiralıks", ReplyAction="http://tempuri.org/IEmlakService/GetKiralıksResponse")]
        Emlak.UI.EmlakServiceReference.Kiralık[] GetKiralıks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/GetKiralıks", ReplyAction="http://tempuri.org/IEmlakService/GetKiralıksResponse")]
        System.Threading.Tasks.Task<Emlak.UI.EmlakServiceReference.Kiralık[]> GetKiralıksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/AddKiralık", ReplyAction="http://tempuri.org/IEmlakService/AddKiralıkResponse")]
        void AddKiralık(Emlak.UI.EmlakServiceReference.Kiralık kiralık);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/AddKiralık", ReplyAction="http://tempuri.org/IEmlakService/AddKiralıkResponse")]
        System.Threading.Tasks.Task AddKiralıkAsync(Emlak.UI.EmlakServiceReference.Kiralık kiralık);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/RemoveKiralık", ReplyAction="http://tempuri.org/IEmlakService/RemoveKiralıkResponse")]
        void RemoveKiralık(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/RemoveKiralık", ReplyAction="http://tempuri.org/IEmlakService/RemoveKiralıkResponse")]
        System.Threading.Tasks.Task RemoveKiralıkAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/EditKiralık", ReplyAction="http://tempuri.org/IEmlakService/EditKiralıkResponse")]
        void EditKiralık(Emlak.UI.EmlakServiceReference.Kiralık kiralık);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/EditKiralık", ReplyAction="http://tempuri.org/IEmlakService/EditKiralıkResponse")]
        System.Threading.Tasks.Task EditKiralıkAsync(Emlak.UI.EmlakServiceReference.Kiralık kiralık);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/GetSatılıks", ReplyAction="http://tempuri.org/IEmlakService/GetSatılıksResponse")]
        Emlak.UI.EmlakServiceReference.Satılık[] GetSatılıks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/GetSatılıks", ReplyAction="http://tempuri.org/IEmlakService/GetSatılıksResponse")]
        System.Threading.Tasks.Task<Emlak.UI.EmlakServiceReference.Satılık[]> GetSatılıksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/AddSatılık", ReplyAction="http://tempuri.org/IEmlakService/AddSatılıkResponse")]
        void AddSatılık(Emlak.UI.EmlakServiceReference.Satılık satılık);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/AddSatılık", ReplyAction="http://tempuri.org/IEmlakService/AddSatılıkResponse")]
        System.Threading.Tasks.Task AddSatılıkAsync(Emlak.UI.EmlakServiceReference.Satılık satılık);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/RemoveSatılık", ReplyAction="http://tempuri.org/IEmlakService/RemoveSatılıkResponse")]
        void RemoveSatılık(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/RemoveSatılık", ReplyAction="http://tempuri.org/IEmlakService/RemoveSatılıkResponse")]
        System.Threading.Tasks.Task RemoveSatılıkAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/EditSatılık", ReplyAction="http://tempuri.org/IEmlakService/EditSatılıkResponse")]
        void EditSatılık(Emlak.UI.EmlakServiceReference.Satılık satılık);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmlakService/EditSatılık", ReplyAction="http://tempuri.org/IEmlakService/EditSatılıkResponse")]
        System.Threading.Tasks.Task EditSatılıkAsync(Emlak.UI.EmlakServiceReference.Satılık satılık);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmlakServiceChannel : Emlak.UI.EmlakServiceReference.IEmlakService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmlakServiceClient : System.ServiceModel.ClientBase<Emlak.UI.EmlakServiceReference.IEmlakService>, Emlak.UI.EmlakServiceReference.IEmlakService {
        
        public EmlakServiceClient() {
        }
        
        public EmlakServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmlakServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmlakServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmlakServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Emlak.UI.EmlakServiceReference.Users GetUsers(string username, string password) {
            return base.Channel.GetUsers(username, password);
        }
        
        public System.Threading.Tasks.Task<Emlak.UI.EmlakServiceReference.Users> GetUsersAsync(string username, string password) {
            return base.Channel.GetUsersAsync(username, password);
        }
        
        public Emlak.UI.EmlakServiceReference.Müsteri[] GetMüsteris() {
            return base.Channel.GetMüsteris();
        }
        
        public System.Threading.Tasks.Task<Emlak.UI.EmlakServiceReference.Müsteri[]> GetMüsterisAsync() {
            return base.Channel.GetMüsterisAsync();
        }
        
        public Emlak.UI.EmlakServiceReference.Daire[] GetDaires() {
            return base.Channel.GetDaires();
        }
        
        public System.Threading.Tasks.Task<Emlak.UI.EmlakServiceReference.Daire[]> GetDairesAsync() {
            return base.Channel.GetDairesAsync();
        }
        
        public Emlak.UI.EmlakServiceReference.Odalar[] GetOdalars() {
            return base.Channel.GetOdalars();
        }
        
        public System.Threading.Tasks.Task<Emlak.UI.EmlakServiceReference.Odalar[]> GetOdalarsAsync() {
            return base.Channel.GetOdalarsAsync();
        }
        
        public void AddMüsteri(Emlak.UI.EmlakServiceReference.Müsteri müsteri) {
            base.Channel.AddMüsteri(müsteri);
        }
        
        public System.Threading.Tasks.Task AddMüsteriAsync(Emlak.UI.EmlakServiceReference.Müsteri müsteri) {
            return base.Channel.AddMüsteriAsync(müsteri);
        }
        
        public void RemoveMüsteri(int id) {
            base.Channel.RemoveMüsteri(id);
        }
        
        public System.Threading.Tasks.Task RemoveMüsteriAsync(int id) {
            return base.Channel.RemoveMüsteriAsync(id);
        }
        
        public void EditMüsteri(Emlak.UI.EmlakServiceReference.Müsteri müsteri) {
            base.Channel.EditMüsteri(müsteri);
        }
        
        public System.Threading.Tasks.Task EditMüsteriAsync(Emlak.UI.EmlakServiceReference.Müsteri müsteri) {
            return base.Channel.EditMüsteriAsync(müsteri);
        }
        
        public void AddOda(Emlak.UI.EmlakServiceReference.Odalar odalar) {
            base.Channel.AddOda(odalar);
        }
        
        public System.Threading.Tasks.Task AddOdaAsync(Emlak.UI.EmlakServiceReference.Odalar odalar) {
            return base.Channel.AddOdaAsync(odalar);
        }
        
        public void RemoveOda(Emlak.UI.EmlakServiceReference.Odalar odalar) {
            base.Channel.RemoveOda(odalar);
        }
        
        public System.Threading.Tasks.Task RemoveOdaAsync(Emlak.UI.EmlakServiceReference.Odalar odalar) {
            return base.Channel.RemoveOdaAsync(odalar);
        }
        
        public void EditOda(Emlak.UI.EmlakServiceReference.Odalar odalar) {
            base.Channel.EditOda(odalar);
        }
        
        public System.Threading.Tasks.Task EditOdaAsync(Emlak.UI.EmlakServiceReference.Odalar odalar) {
            return base.Channel.EditOdaAsync(odalar);
        }
        
        public void AddDaire(Emlak.UI.EmlakServiceReference.Daire daire) {
            base.Channel.AddDaire(daire);
        }
        
        public System.Threading.Tasks.Task AddDaireAsync(Emlak.UI.EmlakServiceReference.Daire daire) {
            return base.Channel.AddDaireAsync(daire);
        }
        
        public void RemoveDaire(int id) {
            base.Channel.RemoveDaire(id);
        }
        
        public System.Threading.Tasks.Task RemoveDaireAsync(int id) {
            return base.Channel.RemoveDaireAsync(id);
        }
        
        public void EditDaire(Emlak.UI.EmlakServiceReference.Daire daire) {
            base.Channel.EditDaire(daire);
        }
        
        public System.Threading.Tasks.Task EditDaireAsync(Emlak.UI.EmlakServiceReference.Daire daire) {
            return base.Channel.EditDaireAsync(daire);
        }
        
        public Emlak.UI.EmlakServiceReference.MalSahibi[] GetMalSahibis() {
            return base.Channel.GetMalSahibis();
        }
        
        public System.Threading.Tasks.Task<Emlak.UI.EmlakServiceReference.MalSahibi[]> GetMalSahibisAsync() {
            return base.Channel.GetMalSahibisAsync();
        }
        
        public void AddMalSahibi(Emlak.UI.EmlakServiceReference.MalSahibi malSahibi) {
            base.Channel.AddMalSahibi(malSahibi);
        }
        
        public System.Threading.Tasks.Task AddMalSahibiAsync(Emlak.UI.EmlakServiceReference.MalSahibi malSahibi) {
            return base.Channel.AddMalSahibiAsync(malSahibi);
        }
        
        public void RemoveMalSahibi(int id) {
            base.Channel.RemoveMalSahibi(id);
        }
        
        public System.Threading.Tasks.Task RemoveMalSahibiAsync(int id) {
            return base.Channel.RemoveMalSahibiAsync(id);
        }
        
        public void EditMalSahibi(Emlak.UI.EmlakServiceReference.MalSahibi malSahibi) {
            base.Channel.EditMalSahibi(malSahibi);
        }
        
        public System.Threading.Tasks.Task EditMalSahibiAsync(Emlak.UI.EmlakServiceReference.MalSahibi malSahibi) {
            return base.Channel.EditMalSahibiAsync(malSahibi);
        }
        
        public Emlak.UI.EmlakServiceReference.Kiralık[] GetKiralıks() {
            return base.Channel.GetKiralıks();
        }
        
        public System.Threading.Tasks.Task<Emlak.UI.EmlakServiceReference.Kiralık[]> GetKiralıksAsync() {
            return base.Channel.GetKiralıksAsync();
        }
        
        public void AddKiralık(Emlak.UI.EmlakServiceReference.Kiralık kiralık) {
            base.Channel.AddKiralık(kiralık);
        }
        
        public System.Threading.Tasks.Task AddKiralıkAsync(Emlak.UI.EmlakServiceReference.Kiralık kiralık) {
            return base.Channel.AddKiralıkAsync(kiralık);
        }
        
        public void RemoveKiralık(int id) {
            base.Channel.RemoveKiralık(id);
        }
        
        public System.Threading.Tasks.Task RemoveKiralıkAsync(int id) {
            return base.Channel.RemoveKiralıkAsync(id);
        }
        
        public void EditKiralık(Emlak.UI.EmlakServiceReference.Kiralık kiralık) {
            base.Channel.EditKiralık(kiralık);
        }
        
        public System.Threading.Tasks.Task EditKiralıkAsync(Emlak.UI.EmlakServiceReference.Kiralık kiralık) {
            return base.Channel.EditKiralıkAsync(kiralık);
        }
        
        public Emlak.UI.EmlakServiceReference.Satılık[] GetSatılıks() {
            return base.Channel.GetSatılıks();
        }
        
        public System.Threading.Tasks.Task<Emlak.UI.EmlakServiceReference.Satılık[]> GetSatılıksAsync() {
            return base.Channel.GetSatılıksAsync();
        }
        
        public void AddSatılık(Emlak.UI.EmlakServiceReference.Satılık satılık) {
            base.Channel.AddSatılık(satılık);
        }
        
        public System.Threading.Tasks.Task AddSatılıkAsync(Emlak.UI.EmlakServiceReference.Satılık satılık) {
            return base.Channel.AddSatılıkAsync(satılık);
        }
        
        public void RemoveSatılık(int id) {
            base.Channel.RemoveSatılık(id);
        }
        
        public System.Threading.Tasks.Task RemoveSatılıkAsync(int id) {
            return base.Channel.RemoveSatılıkAsync(id);
        }
        
        public void EditSatılık(Emlak.UI.EmlakServiceReference.Satılık satılık) {
            base.Channel.EditSatılık(satılık);
        }
        
        public System.Threading.Tasks.Task EditSatılıkAsync(Emlak.UI.EmlakServiceReference.Satılık satılık) {
            return base.Channel.EditSatılıkAsync(satılık);
        }
    }
}
