//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmlakDbEntities : DbContext
    {
        public EmlakDbEntities()
            : base("name=EmlakDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Daire> Daire { get; set; }
        public virtual DbSet<Kiralık> Kiralık { get; set; }
        public virtual DbSet<MalSahibi> MalSahibi { get; set; }
        public virtual DbSet<Müsteri> Müsteri { get; set; }
        public virtual DbSet<Odalar> Odalar { get; set; }
        public virtual DbSet<Satılık> Satılık { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
