//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class MalSahibi
    {
        [DataMember]
        public int SahipId { get; set; }
        [DataMember]
        public string SahipAdı { get; set; }
        [DataMember]
        public string SahipSoyadı { get; set; }
        [DataMember]
        public Nullable<int> SahipTc { get; set; }
        [DataMember]
        public string SahipEmail { get; set; }
    }
}
