//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Müsteri
    {
        [DataMember]
        public int MüsteriId { get; set; }
        [DataMember]
        public string MüsteriAdı { get; set; }
        [DataMember]
        public string MüsteriSoyadı { get; set; }
        [DataMember]
        public Nullable<int> MüsteriTc { get; set; }
        [DataMember]
        public string MüsteriMail { get; set; }
    }
}
