//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Odalar
    {
        [DataMember]
        public int OdaId { get; set; }
        [DataMember]
        public string OdaAdı { get; set; }
        [DataMember]
        public Nullable<int> OdaSayısı { get; set; }
    }
}
